services:
  - type: web
    name: talkure-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: true
