services:
  - type: web
    name: django-chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatapp.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatapp.settings
      - key: SECRET_KEY
        generateValue: true
