services:
  - type: web
    name: django-chat-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatapp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
            name: redis
            property: connectionString
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        fromDatabase:
            name: chat_app
            property: connectionString

  - type: redis
    name: redis
    plan: free

databases:
  - name: chat_app
    plan: free
