# Generated by Django 5.2.3 on 2025-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="group_pics/default.svg",
                null=True,
                upload_to="group_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pic/default.svg",
                null=True,
                upload_to="profile_pic/users/",
            ),
        ),
    ]
