# Generated by Django 5.2.1 on 2025-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pic/default.png",
                null=True,
                upload_to="profile_pic/users/",
            ),
        ),
    ]
